-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN     "costPerMessage" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "costPerUser" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'BRL';
